### ISSUE TITLE
TypeError: disconnect() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by ferocide001** [ferocide001/smart-board#1]
# Branch:
wetter_widget

# Recreation
open screensaver.html
click to wake up home.html
websocket for weather tries to connect
connects 
but still throws this error after connection

# Full Error
HTTP GET /static/styles/home_page.css 304 [0.07, 127.0.0.1:49442]
WebSocket HANDSHAKING /ws/weather/ [127.0.0.1:49444]
WebSocket CONNECT /ws/weather/ [127.0.0.1:49444]
Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/consumer.py", line 125, in dispatch
    handler(message)
  File "/home/fabian/.local/share/virtualenvs/smart-board-IfAd-X0W/lib/python3.8/site-packages/channels/generic/websocket.py", line 105, in websocket_disconnect
    self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given

**Comment by ferocide001** [comment]
Ist kein app breaking issue also können wir uns mit dem fixen Zeit lasse!
Wirft halt nur nen nervigen fetten error code.
Man kann danach aber alles weiter benutzen

**Comment by Addi-jpg** [comment]
-very good issue solving from Fabian

**Comment by ferocide001** [comment]
Give all websocket disconnect functions an argument. This eliminates the risk of passing an argument to other websockt disconnect function, because it has no place in first websocket
